wechat:
  appid: wxce445d2e4aea2c00
  appsecret: d924576eb694612ac2831e3bfadb57cf
  access-token-key: wx.user.accesstoken
  refresh-token-key: wx.user.refreshtoken
  initial-pwd: 123456

pbi:
  resource: https://analysis.windows.net/powerbi/api
  client_id: 123
  grant_type: 123
  password: 123
  username: 123
  client_secret:
  aad_token_name: fengtoos_pbi_token


