server:
  port: 8080

fengtoos:
  devaddress: 127.0.0.1
  prodaddress: 192.168.68.79

spring:
  application:
    name: shop-admin
  profiles:
    include:
    active: dev
  jackson:
    generator:
      write_numbers_as_strings: true

mybatis-plus:
  mapperLocations: classpath*:mappers/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.zhuofengyuan.wechat.shop.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


