server:
  port: 8080

fengtoos:
  ipaddress: 127.0.0.1
  pbiaddress: 192.168.68.79

spring:
  application:
    name: shop-admin
  profiles:
    include:
  datasource:
    druid:
      url: jdbc:mysql://${fengtoos.pbiaddress}:3306/wechat_shop?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
      username: root
      password: Mls2020*
      initial-size: 5
      max-active: 20
      min-idle: 10
      max-wait: 10

  # redis 配置
  redis:
    #数据库索引
    database: 1
    host: ${fengtoos.pbiaddress}
    port: 6379
    password: mls2020*

  jackson:
    generator:
      write_numbers_as_strings: true

mybatis-plus:
  mapperLocations: classpath*:mappers/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.zhuofengyuan.wechat.shop.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

zk:
  host: ${fengtoos.pbiaddress}:2181

file:
  temppath: temp


