spring:
  datasource:
    druid:
      url: jdbc:mysql://${fengtoos.prodaddress}:3306/wechat_shop?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
      username: root
      password: Mls2020*
      initial-size: 5
      max-active: 20
      min-idle: 10
      max-wait: 10

  # redis 配置
  redis:
    #数据库索引
    database: 1
    host: ${fengtoos.prodaddress}
    port: 6379
    password: mls2020*

  jackson:
    generator:
      write_numbers_as_strings: true

zk:
  host: ${fengtoos.prodaddress}:2181

file:
  temppath: temp


